export const RECEIVE_USERS = 'RECEIVE_USERS';

export const SET_AUTHED_USER_ID = 'SET_AUTHED_USER_ID';

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';

export const SAVE_QUESTION = 'SAVE_QUESTION';
