export const FETCH_USERS = 'FETCH_USERS';

export const FETCH_USERS_COMPLETED = 'FETCH_USERS_COMPLETED';

export const SET_AUTHED_USER_ID = 'SET_AUTHED_USER_ID';

export const SET_AUTHED_USER_ID_COMPLETED = 'SET_AUTHED_USER_ID_COMPLETED';

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

export const FETCH_QUESTIONS_COMPLETED = 'FETCH_QUESTIONS_COMPLETED';

export const SAVE_QUESTION = 'SAVE_QUESTION';

export const SAVE_QUESTION_COMPLETED = 'SAVE_QUESTION_COMPLETED';

export const SUBMIT_VOTE_STARTED = 'SUBMIT_VOTE_STARTED';
